print("What do you call a band of killer whales?")
input("")
print("An orca-stra!")
input("")
print("What do you call a cheese that isn't yours?")
input("")
print("Nacho Cheese!")
input("")
print("Why did the cow cross the road?")
input("")
print("To get to the moo-vies!!!!!!")