print("When is the best time to go to the dentist?")
input ("")
print ("Tooth-hurty")
input ("")
print ("why are elephants wrinkly?")
input ("")
print ("because you can't iron them")
input ("")
print ("What do you call a can opener that doesn't work?")
input ("")
print ("a can't opener")
