name = input ("Hi what is your name?")
print (f"hello{name}, we're going to write a short story")
print ("")
print ("")
date = input ("Give me a date, anywhere in time")
location = input ("Now give me a location")
vehicle = input ("Give me a vehicle, a boat, plane, car etc.")
noun = input ("Great, now give me a noun")
animal = input ("Now give me a weird animal, like something very random.")
adjective = input ("Finally give me an adjective.")
print ("")
print ("Good job you're done!")
print ("")
print ("")
print (f"Once upon a time, in {date}, there was a person named {name}. {name} drove in the {vehicle} to {location}. {name} walked around for a while, and then found a {noun} and picked it up and ate it. Then {name} turned into a {adjective} {animal}.") 
print ("The end!")
print (":)")