print("My name is Josh")
print("I am from New Jersey")
print("My favorite food is quiche")
print("Now I want to learn about you")
their_name = input("What's your name?")
print(f"Hi {their_name}, nice to meet you")
print("   __   __   ____  _  _    __ _  _  _  ____  __  ____  __ _  __  ")
print(" _(  ) /  \ / ___)/ )( \  (  / )/ )( \(  _ \(  )/ ___)(  / )/  \ ")
print("/ \) \(  O )\___ \) __ (   )  ( ) \/ ( )   / )( \___ \ )  ((  O )")
print("\____/ \__/ (____/\_)(_/  (__\_)\____/(__\_)(__)(____/(__\_)\__/ ")